theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "battery"
upower = false
format = "{percentage}% {time}"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}/{MTg}GB({Mup}%)"
format_swap = "{SUg}/{STg}GB({SUp}%)"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "uptime"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
